### ISSUE TITLE
Public server with Crimson Scales - ? Monsters

### ISSUE THREAD

**Issue by dtmcgregor** [Lurkars/ghs-server#13]
When playing a Crimson Scales scenario on the public server gloomhaven-secretariat.de, the scenario starts up with monsters with a ? for a number that can't be killed. See attached pic for an example. Changing the edition to Gloomhaven has a similar result. A workaround is to manually remove the monster and then readd the monster, at which point everything is normal. 

![ghs](https://user-images.githubusercontent.com/5069361/225825124-a5b65de5-ecc6-4944-92b8-26e8efbfad6c.jpg)

**Comment by Lurkars** [comment]
Thanks, I will take a look. In future, please put those tickets to the Gloomhaven Secretariat repository, because this doesn't seem server related.

**Comment by Lurkars** [comment]
This is the automatic standee feature. Since you not have enabled random standees, the standee number is unknown and allowing therefore showing ? instead of a number. Just click on the standee to set it's standee number! It's not a bug, it's a feature! If you don't want to automatically add the required standees for you, there's also a setting to disable it.

**Comment by Lurkars** [comment]
This is by the way not server related. Same result on not connected client. It's a feature that you can disable if you don't like it.

**Comment by dtmcgregor** [comment]
Great, thanks very much for looking into it so fast!
