### ISSUE TITLE
Creating Local Server: Only LocalHost can connect

### ISSUE THREAD

**Issue by Hendrycks12** [Lurkars/ghs-server#20]
Hey, I've followed the Server instructions and I can see in the Java window my game ID, etc with my IP and default port (8080).

When I try connecting to the same with anything but the machine running the server, it won't work.

If I try editing the application.properties file with any additional lines to attempt to change the port, check for updates, etc - the server will no longer run either.

Thanks in advance and if you need any more info please let me know!

**Comment by Lurkars** [comment]
Important question is the client! If you try to access an unsecured server with a client running with HTTPS,almost every browser will block the connection. So either setup SSL in server or serve the client via the server and access both client and server from your local unsecure connection!

**Comment by Hendrycks12** [comment]
> Important question is the client! If you try to access an unsecured server with a client running with HTTPS,almost every browser will block the connection. So either setup SSL in server or serve the client via the server and access both client and server from your local unsecure connection!

I'm serving the client now on my PC and can connect with my wife and I's phones, but only by going to the IP and port in the address bar.

Is there a way to have the 'App' version work? I like the full screen nature of it, and just adding the Website to the home screen isn't as nice. So happy to have it working!

Thanks!

**Comment by Lurkars** [comment]
> Is there a way to have the 'App' version work? I like the full screen nature of it, and just adding the Website to the home screen isn't as nice. So happy to have it working!

It all comes down to SSL, the local version is technically completely the same as hosted, but also most browser do not allow install a site as PWA without SSL. Since simply running this local with SSL enabled, I think using the self-signed certificate also won't allow. But at least you can try following:

Enable SSL support, open Server site on phone and accept the self-signed certificate. Afterwards, use official hosted client and connect to your local server with `secure` option. Hopefully that should work.
