### ISSUE TITLE
Missing states

### ISSUE THREAD

**Issue by EricE-MW** [Lurkars/ghs-server#26]
When creating your own server it often sais "missing states" in menu (see screenshot below).
This often leads to unsynchronized states between server/clients. It appears when changing some settings and "synchronize settings" is active.

![Screenshot 2024-02-26 093621](https://github.com/Lurkars/ghs-server/assets/91049957/7dcf5825-2b4c-4208-b290-4e64e0a301dd)

**Comment by Lurkars** [comment]
Can you try to investigate further to see exactly when you get those state? Storing settings should never change the game state and change the undo stack. I also cannot reproduce this. So in general this only happens if a client is not connected and therefore missing states in between or if there is a bug in the client to trigger an event twice without updating server state or so. (Usually simple coding bugs and easy to fix.) So that's why I sadly need to ask for just more details...

**Comment by eXitus132** [comment]
We didnt have seen this Issue anymore- i guess it was different client/server Versions!
